sudo: false

language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

env:
  - LARAVEL_VERSION="5.3.*"
  - LARAVEL_VERSION="5.4.*"

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction
  - composer info -i

script:
  - vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: always